services:
  postgres:
    image: postgres
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_PASSWORD
  authentication:
    build:
      context: .
      dockerfile: ./apps/authentication/Dockerfile
      target: development
    command: pnpm run start:dev authentication
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  tasks:
    build:
      context: .
      dockerfile: ./apps/tasks/Dockerfile
      target: development
    command: pnpm run start:dev tasks
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app
  clients:
    build:
      context: .
      dockerfile: ./apps/clients/Dockerfile
      target: development
    command: pnpm run start:dev clients
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
  cars:
    build:
      context: .
      dockerfile: ./apps/cars/Dockerfile
      target: development
    command: pnpm run start:dev cars
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app