services:
  postgres:
    image: postgres
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_PASSWORD
  cars:
    build:
      context: .
      dockerfile: ./apps/cars/Dockerfile
      target: development
    command: pnpm run start:dev cars
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app