services:
  postgres:
    image: postgres
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_PASSWORD

  invoices_postgres:
    image: postgres
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql

  authentication:
    build:
      context: .
      dockerfile: ./apps/authentication/Dockerfile
      target: development
    command: pnpm run start:dev authentication
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app

  tasks:
    build:
      context: .
      dockerfile: ./apps/tasks/Dockerfile
      target: development
    command: pnpm run start:dev tasks
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app

  invoices:
    build:
      context: .
      dockerfile: ./apps/invoices/Dockerfile
      target: development
    command: pnpm run start:dev invoices
    ports:
      - '3004:3004'
    volumes:
      - .:/usr/src/app
    depends_on:
      - invoices_postgres

  clients:
    build:
      context: .
      dockerfile: ./apps/clients/Dockerfile
      target: development
    command: pnpm run start:dev clients
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
      
  cars:
    build:
      context: .
      dockerfile: ./apps/cars/Dockerfile
      target: development
    command: pnpm run start:dev cars
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app